#!/usr/bin/env php
<?php

	require __DIR__.'/php-source/converter.php';

	// TODO: filename
	$file = $argv[1];
	$xml = simplexml_load_file($file);

	$generator = new Converter();
	$tex = $generator->convert($xml);

	echo $tex;


